version: "3"
services:
  postgres01:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - "./inital.sql:/docker-entrypoint-initdb.d/initial.sql"        
  
    
